instances:
  - name: elasticsearch_1
    dns:
      - elasticsearch_1
      - elasticsearch_1.local
      - localhost
    ip:
      - 0.0.0.0
      - 127.0.0.1

  - name: kibana_1
    dns:
      - kibana_1
      - localhost
    ip:
      - 0.0.0.0
      - 127.0.0.1

  - name: apm_server_1
    dns:
      - apm_server_1
      - localhost
    ip:
      - 0.0.0.0
      - 127.0.0.1

  - name: nginx
    dns:
      - nginx
      - nginx_1
      - localhost
      - application.local
    ip:
      - 0.0.0.0
      - 127.0.0.1
