# Create the certificates for the stack:
#
#     docker-compose --file certificates-create.yml up
#
# See: https://www.elastic.co/guide/en/elasticsearch/reference/current/configuring-tls-docker.html

version: "3.7"

services:
  create_certs:
    image: docker.elastic.co/elasticsearch/elasticsearch:${VERSION}
    container_name: certificates_generator
    user: root
    working_dir: /usr/share/elasticsearch
    command: >
      bash -c '
        yum install -y -q -e 0 unzip;
        if [[ ! -f /certificates/bundle.zip ]]; then
          bin/elasticsearch-certutil cert \
            --pem \
            --days 365 \
            --keep-ca-key \
            --in config/certificates/certificates-config.yml \
            --out /certificates/bundle.zip;
          unzip /certificates/bundle.zip -d /certificates;
        fi;
        chown -R 1000:0 /certificates
      '
    volumes:
      - ./certificates:/certificates
      - ./certificates-config.yml:/usr/share/elasticsearch/config/certificates/certificates-config.yml
