instances:
  - name: nginx
    dns:
      - demo_nginx
      - demo_nginx_1
      - localhost
      - application.local
      - "*.bc.googleusercontent.com"
    ip:
      - 0.0.0.0
      - 127.0.0.1

  - name: elasticsearch
    dns:
      - demo_elasticsearch_1
      - demo_elasticsearch_1.local
      - demo_elasticsearch_2
      - demo_elasticsearch_2.local
      - demo_elasticsearch_3
      - demo_elasticsearch_3.local
      - localhost
    ip:
      - 0.0.0.0
      - 127.0.0.1

  - name: kibana
    dns:
      - demo_kibana_1
      - demo_kibana_1.local
      - localhost
    ip:
      - 0.0.0.0
      - 127.0.0.1

  - name: apm_server
    dns:
      - demo_apm_server_1
      - localhost
    ip:
      - 0.0.0.0
      - 127.0.0.1
