# https://github.com/elastic/apm-agent-python/pull/1873
FROM python:3.12-slim

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN apt-get update && \
  apt-get install --yes --no-install-recommends cron curl procps && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY cron_run.sh /app/
COPY crontab /etc/cron.d/demo-job

COPY script.py /app/

CMD /app/cron_run.sh
