filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true
      templates:
        # Nginx
        - condition: { contains: { docker.container.image: nginx }}
          config:
            - module: nginx
              access: { enabled: true, var.paths: ["/var/log/nginx/log/access.log*"] }
              error:  { enabled: true, var.paths: ["/var/log/nginx/log/error.log*"]  }
        # Elasticsearch
        - condition: { contains: { docker.container.image: elasticsearch }}
          config:
            - module: elasticsearch
              audit:       { enabled: true }
              deprecation: { enabled: true }
              gc:          { enabled: true }
              server:      { enabled: true }
              slowlog:     { enabled: true }
        # Redis
        - condition: { contains: { docker.container.image: redis }}
          config:
            - module: redis
              log:
                var.paths: ["/var/log/redis/redis.log*"]
              slowlog:
                var.hosts: ["redis://${data.docker.container.name}:${data.port}"]
                var.password: "${REDIS_PASSWORD}"

processors:
  - add_host_metadata: ~
  - add_docker_metadata: ~
  - add_cloud_metadata: ~

tags: ['service-A']
fields: { environment: 'staging' }

setup:
  kibana:
    host: https://kibana_1:5601
    username: "elastic"
    password: "${ELASTIC_PASSWORD}"
    ssl.enabled: true
    ssl.certificate_authorities: ["/usr/share/filebeat/config/certificates/ca/ca.crt"]
  dashboards: { enabled: true,  retry: { enabled: true, interval: 10s }}

output.elasticsearch:
  hosts: ["https://elasticsearch_1:9200"]
  username: "elastic"
  password: "${ELASTIC_PASSWORD}"
  ssl.certificate_authorities: ["/usr/share/filebeat/config/certificates/ca/ca.crt"]

monitoring:
  enabled: true
  elasticsearch.hosts: ["http://elasticsearch_1:9200"]
  elasticsearch.username: "elastic"
  elasticsearch.password: "${ELASTIC_PASSWORD}"
  elasticsearch.ssl.certificate_authorities: ["/usr/share/filebeat/config/certificates/ca/ca.crt"]
