metricbeat.modules:
  - module: system
    metricsets: ["core", "cpu", "load", "diskio", "memory", "network", "process", "socket"]
    process.cgroups.enabled: true

  - module: docker
    metricsets: ["container", "cpu", "diskio", "healthcheck", "info", "image", "memory", "network"]
    hosts: ["unix:///var/run/docker.sock"]
    period: 10s

metricbeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true
      templates:
        # Nginx
        - condition: { contains: { docker.container.image: nginx }}
          config:
            - module: nginx
              metricsets: ["stubstatus"]
              hosts: ["https://${data.docker.container.name}:443"]
              headers: { Authorization: "Bearer secret" }
              ssl.certificate_authorities: ["/usr/share/metricbeat/config/certificates/ca/ca.crt"]
              period: 5s
        # Redis
        - condition: { contains: { docker.container.image: redis }}
          config:
            - module: redis
              metricsets: ["info", "keyspace"]
              period: 10s
              hosts: ["redis://${data.host}:${data.port}"]
              password: secret

processors:
  - add_host_metadata: ~
  - add_docker_metadata: ~
  - add_cloud_metadata: ~

tags: ['service-A']
fields: { environment: 'staging' }

setup:
  kibana:
    host: https://kibana_1:5601
    username: "elastic"
    password: "${ELASTIC_PASSWORD}"
    ssl.enabled: true
    ssl.certificate_authorities: ["/usr/share/metricbeat/config/certificates/ca/ca.crt"]
  dashboards: { enabled: true,  retry: { enabled: true, interval: 10s }}

output.elasticsearch:
  hosts: ["https://elasticsearch_1:9200"]
  username: "elastic"
  password: "${ELASTIC_PASSWORD}"
  ssl.certificate_authorities: ["/usr/share/metricbeat/config/certificates/ca/ca.crt"]

monitoring:
  enabled: true
  elasticsearch.hosts: ["http://elasticsearch_1:9200"]
  elasticsearch.username: "elastic"
  elasticsearch.password: "${ELASTIC_PASSWORD}"
  elasticsearch.ssl.certificate_authorities: ["/usr/share/metricbeat/config/certificates/ca/ca.crt"]
